apiVersion: v1
kind: Service
metadata:
  name: jobsathi-ui-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: jobsathi-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30085   # Tapaiko browser ma access garna milne port
